# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Portfolio Movement

# Model Form Field configuration
form: $/piratmac/smmm/models/portfoliomovement/fields.yaml

# Model Class name
modelClass: Piratmac\Smmm\Models\PortfolioMovement