# ===================================
#  Form Behavior Config
# ===================================

# Model Form Field configuration
form: $/piratmac/smmm/models/portfolio/fields.yaml

# Model Class name
modelClass: Piratmac\Smmm\Models\Portfolio